// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeNGhdpfa4QBYOYymS_qPc4YypMHACIfQ',
    appId: '1:129283343623:web:f32022bd340e38f8a731a2',
    messagingSenderId: '129283343623',
    projectId: 'flutter-chat-app-9f823',
    authDomain: 'flutter-chat-app-9f823.firebaseapp.com',
    storageBucket: 'flutter-chat-app-9f823.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIWGWbwMoi8GW-aT_NuwmPQ3jGafZiZDU',
    appId: '1:129283343623:android:c6e2114c7bef7d2ba731a2',
    messagingSenderId: '129283343623',
    projectId: 'flutter-chat-app-9f823',
    storageBucket: 'flutter-chat-app-9f823.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyA0O142r7J8gN2GpmkJG_8eTmYArVyA4',
    appId: '1:129283343623:ios:23761baf66a4a641a731a2',
    messagingSenderId: '129283343623',
    projectId: 'flutter-chat-app-9f823',
    storageBucket: 'flutter-chat-app-9f823.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyA0O142r7J8gN2GpmkJG_8eTmYArVyA4',
    appId: '1:129283343623:ios:23761baf66a4a641a731a2',
    messagingSenderId: '129283343623',
    projectId: 'flutter-chat-app-9f823',
    storageBucket: 'flutter-chat-app-9f823.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeNGhdpfa4QBYOYymS_qPc4YypMHACIfQ',
    appId: '1:129283343623:web:c0a1ab72235ae964a731a2',
    messagingSenderId: '129283343623',
    projectId: 'flutter-chat-app-9f823',
    authDomain: 'flutter-chat-app-9f823.firebaseapp.com',
    storageBucket: 'flutter-chat-app-9f823.firebasestorage.app',
  );

}